"""Ports: what the application layer needs from adapters, as Protocols.

Nothing here mentions pandas, DuckDB or the library. The engine port speaks
in plain Python containers (``Table`` dicts) so that services and routers stay
free of dataframes.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Protocol

from wise_workbench.domain import (
    CaseTable,
    ColumnMapping,
    DatasetVersion,
    Job,
    NormVersion,
    Project,
    Run,
)

Table = dict[str, Any]  # {"columns": [...], "rows": [[...], ...]}
ProgressFn = Callable[[float, str], None]


class Repository(Protocol):
    def add_project(self, p: Project) -> Project: ...
    def get_project(self, project_id: str) -> Project: ...
    def list_projects(self) -> list[Project]: ...
    def set_latest_run(self, project_id: str, run_id: str) -> None: ...
    def add_dataset(self, d: DatasetVersion) -> DatasetVersion: ...
    def update_dataset(self, d: DatasetVersion) -> DatasetVersion: ...
    def get_dataset(self, dataset_id: str) -> DatasetVersion: ...
    def list_datasets(self, project_id: str) -> list[DatasetVersion]: ...
    def add_mapping(self, m: ColumnMapping) -> ColumnMapping: ...
    def get_mapping(self, mapping_id: str) -> ColumnMapping: ...
    def list_mappings(self, dataset_id: str) -> list[ColumnMapping]: ...
    def add_case_table(self, c: CaseTable) -> CaseTable: ...
    def update_case_table(self, c: CaseTable) -> CaseTable: ...
    def get_case_table(self, case_table_id: str) -> CaseTable: ...
    def list_case_tables(self, project_id: str) -> list[CaseTable]: ...
    def add_norm_version(self, n: NormVersion) -> NormVersion: ...
    def get_norm_version(self, norm_version_id: str) -> NormVersion: ...
    def list_norm_versions(self, project_id: str) -> list[NormVersion]: ...
    def next_norm_number(self, norm_id: str) -> int: ...
    def update_norm_status(self, n: NormVersion) -> NormVersion: ...
    def add_run(self, r: Run) -> Run: ...
    def update_run(self, r: Run) -> Run: ...
    def get_run(self, run_id: str) -> Run: ...
    def list_runs(self, project_id: str) -> list[Run]: ...
    def find_run(
        self, project_id: str, *, params_hash: str | None = None, idempotency_key: str | None = None
    ) -> Run | None: ...
    def add_job(self, j: Job) -> Job: ...
    def save_job(self, j: Job) -> Job: ...
    def get_job(self, job_id: str) -> Job: ...
    def list_jobs(self, status: str | None = None, project_id: str | None = None, limit: int = 100) -> list[Job]: ...
    def update_job_fields(self, job_id: str, **fields: Any) -> None: ...
    def claim_job(self, worker_id: str, lease_seconds: float, now: datetime) -> Job | None: ...
    def heartbeat(self, job_id: str, worker_id: str, lease_seconds: float, now: datetime) -> bool: ...


class JobQueue(Protocol):
    def enqueue(self, job: Job) -> Job: ...
    def get(self, job_id: str) -> Job: ...
    def cancel(self, job_id: str) -> Job: ...
    def list(self, status: str | None = None, project_id: str | None = None) -> list[Job]: ...


class Storage(Protocol):
    root: Path

    def project_dir(self, project_id: str) -> Path: ...
    def dataset_dir(self, project_id: str, dataset_id: str) -> Path: ...
    def case_table_dir(self, project_id: str, case_table_id: str) -> Path: ...
    def norm_version_path(self, project_id: str, norm_id: str, version: int) -> Path: ...
    def run_dir(self, project_id: str, run_id: str) -> Path: ...
    def write_json(self, path: Path, data: Any) -> Path: ...
    def write_text(self, path: Path, text: str) -> Path: ...
    def read_json(self, path: Path) -> Any: ...
    def store_upload(self, dest: Path, stream: Any, chunk_size: int = ...) -> tuple[int, str]: ...


class Engine(Protocol):
    """The engine adapter: the only place that runs the library."""

    def library_version(self) -> str: ...
    def validate_norm(self, document: dict[str, Any]) -> tuple[dict[str, Any], str]: ...
    def ingest(self, source: Path, kind: str, dest_dir: Path, progress: ProgressFn) -> dict[str, Any]: ...
    def profile(self, dataset_dir: Path) -> list[dict[str, Any]]: ...
    def preview(self, dataset_dir: Path, rows: int) -> Table: ...
    def validate_mapping(self, dataset_dir: Path, mapping: ColumnMapping, sample: int) -> dict[str, Any]: ...
    def build_case_table(
        self,
        dataset_dir: Path,
        mapping: ColumnMapping,
        dest_dir: Path,
        progress: ProgressFn,
        *,
        provenance: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def check_norm(self, case_table_dir: Path, mapping: ColumnMapping, document: dict[str, Any]) -> dict[str, Any]: ...
    def score_run(
        self,
        run: Run,
        case_table_dir: Path,
        mapping: ColumnMapping,
        document: dict[str, Any],
        dest_dir: Path,
        progress: ProgressFn,
        *,
        content_hash: str = "",
    ) -> dict[str, Any]: ...
    def summary(self, run: Run, ctx: RunContext) -> dict[str, Any]: ...
    def backlog(
        self, run: Run, ctx: RunContext, attributes: list[str], view: str | None, gamma: float | None, min_cases: int
    ) -> Any: ...
    def slice_detail(
        self, run: Run, ctx: RunContext, attributes: list[str], key: list[Any], view: str | None, drilldown: str | None
    ) -> dict[str, Any]: ...
    def trace(self, run: Run, ctx: RunContext, case_id: str) -> dict[str, Any]: ...
    def diagnostics(self, run: Run, ctx: RunContext, attributes: list[str], view: str | None) -> Table: ...
    def signals(
        self, run: Run, ctx: RunContext, constraint_id: str, attributes: list[str] | None, key: list[Any] | None
    ) -> dict[str, Any]: ...
    def flow(
        self,
        run: Run,
        ctx: RunContext,
        attributes: list[str] | None,
        key: list[Any] | None,
        abstraction: float,
        *,
        process: str | None = None,
    ) -> dict[str, Any]: ...
    def read_events(self, dataset_dir: Path, mapping: ColumnMapping) -> Any: ...


@dataclass(frozen=True)
class RunContext:
    """Everything the engine needs to locate a run's inputs and artefacts."""

    run_dir: Path
    case_table_dir: Path
    mapping: ColumnMapping
    document: dict[str, Any]
    views: tuple[str, ...]
    gamma: float
    min_cases: int
    slicings: tuple[tuple[str, tuple[str, ...]], ...] = ()

    def slicing_attributes(self, slicing: str) -> list[str]:
        """Resolve a slicing id or comma-separated attribute list."""
        for sid, attrs in self.slicings:
            if sid == slicing:
                return list(attrs)
        return [a.strip() for a in slicing.split(",") if a.strip()]

    def slicing_id(self, attributes: list[str]) -> str | None:
        for sid, attrs in self.slicings:
            if list(attrs) == list(attributes):
                return sid
        return None
