import { expect, test } from "@playwright/test";

/** The integration runner supplies an explicitly seeded synthetic project/version; never discover a user's workspace. */
const API = process.env.E2E_API_URL;
const PROJECT = process.env.E2E_PROJECT_ID;
const VERSION = process.env.E2E_NORM_VERSION_ID;
const CASE_TABLE = process.env.E2E_CASE_TABLE_ID;
const BASELINE_RUN = process.env.E2E_BASELINE_RUN_ID;
test.skip(!API || !PROJECT || !VERSION || !CASE_TABLE || !BASELINE_RUN, "requires the isolated synthetic backend fixture and E2E_NORM_VERSION_ID / E2E_CASE_TABLE_ID");

test("selected norm values and names survive reload; missing fields are focused and saved decisions persist", async ({ page, request }, testInfo) => {
  page.setDefaultTimeout(15_000);
  const pageErrors: string[] = [];
  page.on("pageerror", error => pageErrors.push(error.message));
  const base = `${API}/api/v1/projects/${encodeURIComponent(PROJECT!)}/norms`;
  const seed = await request.get(`${base}/${encodeURIComponent(VERSION!)}`); expect(seed.ok()).toBe(true);
  const original = await seed.json() as { norm: { name: string; constraints: { id: string; type: string; params: { delta?: number; width?: number } }[] } };
  const constraint = original.norm.constraints.find(c => c.type === "lag");
  expect(constraint, "seed a lag rule and mapped synthetic case table for this workflow").toBeTruthy();
  const baselineURL = `${API}/api/v1/projects/${PROJECT}/runs/${BASELINE_RUN}/signals/${constraint!.id}`;
  const baselineResponse = await request.get(baselineURL); expect(baselineResponse.ok()).toBe(true);
  const baseline = await baselineResponse.json();
  expect(baseline.threshold).toBe(10);
  expect(baseline.stats.shareBeyondThreshold).toBe(0.5);
  const uncalibrated = structuredClone(original.norm);
  uncalibrated.constraints.find(c => c.id === constraint!.id)!.params.delta = (constraint!.params.delta ?? 1) + 1;
  const draftResponse = await request.post(base, { data: { norm: uncalibrated, parentId: VERSION, note: "Synthetic changed threshold awaiting calibration" } });
  expect(draftResponse.ok()).toBe(true);
  const draft = await draftResponse.json() as { id: string };
  await page.goto(`/p/${PROJECT}/norms/${draft.id}?tab=constraints&constraint=${encodeURIComponent(constraint!.id)}&caseTable=${encodeURIComponent(CASE_TABLE!)}`);
  // This journey exercises required rationale fields; Guided drafts deliberately make them optional.
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await page.getByRole("combobox", { name: "Authoring mode", exact: true }).selectOption("expert");
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await page.getByRole("button", { name: "Mark reviewed", exact: true }).click();
  const dialog = page.getByTestId("sign-norm");
  await expect(dialog.getByRole("list", { name: "Required decisions" })).toBeVisible();
  await expect(dialog.getByLabel("Who signs it")).toHaveCount(0);
  await expect(dialog.getByRole("button", { name: "Save 0 decisions as new draft" })).toBeDisabled();
  await dialog.getByRole("button", { name: "Record decision", exact: true }).click();
  await expect(dialog.getByLabel("Reason for this constraint (required)")).toBeFocused();
  await expect(dialog.getByLabel("Reason for this constraint (required)")).toHaveAttribute("aria-invalid", "true");
  await page.screenshot({ path: testInfo.outputPath("preflight.png"), fullPage: true });
  const refusedVersion = await (await request.get(`${base}/${draft.id}`)).json() as { status: string; author?: string };
  expect(refusedVersion.status).toBe("draft");
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("button", { name: "the rule", exact: true }).click();
  await page.getByLabel("Constraint name", { exact: true }).fill("");
  await page.getByRole("button", { name: "Save as the next version" }).click();
  await expect(page.getByLabel("Constraint name", { exact: true })).toBeFocused();
  await expect(page.getByLabel("Constraint name", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await page.getByLabel("Constraint name", { exact: true }).fill("Invoice follows receipt within 12 days");
  await page.getByLabel("within", { exact: true }).fill(String((constraint!.params.delta ?? 1) + 2));
  await page.getByRole("button", { name: "Save as the next version" }).click();
  await expect(page.getByLabel("why this change (required)", { exact: true })).toBeFocused();
  await expect(page.getByLabel("who owns it (required)", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await page.screenshot({ path: testInfo.outputPath("required-fields.png"), fullPage: true });
  await page.getByLabel("why this change (required)", { exact: true }).fill("Synthetic service decision");
  await page.getByLabel("who owns it (required)", { exact: true }).fill("Calibration owner");
  const createdResponse = page.waitForResponse(r => r.url() === base && r.request().method() === "POST");
  await page.getByRole("button", { name: "Save as the next version" }).click();
  const response = await createdResponse; expect(response.status()).toBe(201);
  const created = await response.json() as { id: string };
  await expect(page).toHaveURL(new RegExp(`/norms/${created.id}\\?`));
  await expect(page.getByTestId("saved-calibration")).toContainText("Synthetic service decision");
  await page.reload();
  await expect(page.getByTestId("saved-calibration")).toContainText("Calibration owner");
  expect(new URL(page.url()).searchParams.get("caseTable")).toBe(CASE_TABLE);
  await expect(page.getByText("Invoice follows receipt within 12 days", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "the numbers", exact: true }).click();
  await expect(page.getByLabel(/Target \(/)).toHaveValue("12");
  await expect(page.getByLabel(/Tolerance width \(/)).toHaveValue("20");
  const calibration = page.getByRole("region", { name: "Threshold calibration", exact: true });
  await expect(calibration.getByRole("heading", { name: "Exact preview · saved → proposed", exact: true })).toBeVisible();
  // The new lens distinguishes four native measurements from all five evaluated cases.
  // One missing measurement is penalized by this rule: 1/4 above target is not the 2/5 violation share.
  await expect(calibration).toContainText("4 finite measurements / 5 applicable cases");
  await expect(calibration.locator("dl > div").filter({ hasText: "Violating / evaluated cases" }).getByRole("definition")).toHaveText("2 / 5 → 2 / 5");
  await expect(calibration.locator("dl > div").filter({ hasText: "Violation share" }).getByRole("definition")).toHaveText(/40\.0\s?% → 40\.0\s?%/);
  await expect(calibration).toContainText("1 missing native measurements");
  await expect(calibration).not.toContainText("About");
  await expect(calibration.getByText("Saved rule: Record Invoice Receipt follows Record Goods Receipt within 12 days, with 20 days of tolerance", { exact: true })).toBeVisible();
  await expect(calibration.getByRole("group", { name: /Distribution in days;/ })).toBeVisible();
  const preview = await request.get(`${base}/${created.id}/signals/${constraint!.id}?caseTableId=${CASE_TABLE}`);
  expect(preview.ok()).toBe(true);
  const previewBody = await preview.json();
  expect(previewBody.normVersionId).toBe(created.id);
  expect(previewBody.threshold).toBe(12);
  expect(previewBody.stats.n).toBe(4);
  expect(previewBody.stats.shareBeyondThreshold).toBe(0.25);
  expect(previewBody.saturation).toBe(32);
  await page.evaluate("window.scrollTo(0, 0)");
  await page.screenshot({ path: testInfo.outputPath("calibration.png"), fullPage: true });
  await expect(page.getByTestId("saved-calibration").locator("time")).toHaveAttribute("datetime", /\d{4}-\d{2}-\d{2}T/);

  await page.getByRole("button", { name: "Mark reviewed", exact: true }).click();
  await dialog.getByLabel("Who signs it").fill("Explicit reviewer");
  await dialog.getByRole("button", { name: "Mark reviewed", exact: true }).click();
  await expect(dialog).toBeHidden();
  await page.reload(); await expect(page.getByText("signed by Explicit reviewer", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Approve this version", exact: true }).click();
  await dialog.getByLabel("Who signs it").fill("Explicit approver");
  await dialog.getByRole("button", { name: "Approve this version", exact: true }).click();
  await expect(dialog).toBeHidden();
  await page.reload(); await expect(page.getByText("signed by Explicit approver", { exact: true })).toBeVisible();

  await page.evaluate("window.scrollTo(0, 0)");
  await page.screenshot({ path: testInfo.outputPath("approved.png"), fullPage: true });
  await page.getByRole("button", { name: "Rename norm", exact: true }).click();
  const rename = page.getByRole("dialog", { name: "Rename norm", exact: true });
  await rename.getByLabel("Norm name", { exact: true }).fill("");
  await rename.getByRole("button", { name: "Save as the next version" }).click();
  await expect(rename.getByLabel("Norm name", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await expect(rename.getByLabel("Norm name", { exact: true })).toBeFocused();
  await rename.getByLabel("Norm name", { exact: true }).fill("Purchasing targets for the walkthrough");
  await rename.getByLabel("why this change (required)", { exact: true }).fill("Name our purchasing targets");
  await rename.getByLabel("who owns it (required)", { exact: true }).fill("Norm owner");
  await rename.getByRole("button", { name: "Save as the next version" }).click();
  await expect(rename).toBeHidden();
  await page.reload();
  await expect(page.getByRole("heading", { name: /Purchasing targets for the walkthrough/ })).toBeVisible();
  await page.getByRole("button", { name: "the numbers", exact: true }).click();
  await expect(page.getByLabel(/Target \(/)).toHaveValue("12");
  await expect(page.getByTestId("saved-calibration")).toContainText("Calibration owner");
  await page.getByRole("button", { name: "who it applies to", exact: true }).click();
  await page.getByLabel("Not applicable to this log", { exact: false }).check();
  await page.getByRole("button", { name: "Save as the next version" }).click();
  await expect(page.getByLabel("why (required)", { exact: true })).toBeFocused();
  await expect(page.getByLabel("why (required)", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await page.getByLabel("why (required)", { exact: true }).fill("The synthetic extract cannot evaluate this expectation");
  await page.getByLabel("why this change (required)", { exact: true }).fill("Record the scope decision");
  await page.getByLabel("who owns it (required)", { exact: true }).fill("Scope owner");
  await page.getByRole("button", { name: "Save as the next version" }).click();
  await expect(page.getByTestId("saved-exclusions")).toContainText("The synthetic extract cannot evaluate this expectation");
  await page.reload();
  await expect(page.getByTestId("saved-exclusions")).toContainText("Scope owner");
  await expect(page.getByTestId("saved-exclusions").locator("time")).toHaveAttribute("datetime", /\d{4}-\d{2}-\d{2}T/);
  expect(new URL(page.url()).searchParams.get("caseTable")).toBe(CASE_TABLE);
  await page.screenshot({ path: testInfo.outputPath("exclusion.png"), fullPage: true });
  await expect(page.getByRole("heading", { name: /Purchasing targets for the walkthrough/ })).toBeVisible();
  await expect(page.getByTestId("saved-exclusions")).toContainText("Invoice follows receipt within 12 days");
  expect((await (await request.get(`${base}/${VERSION}`)).json()).norm).toEqual(original.norm);
  expect(await (await request.get(baselineURL)).json()).toEqual(baseline);
  // Reproduce the seven long definitions seen in review without changing any real workspace.
  const longDescription = "This synthetic constraint describes the agreed payment timing target and the business scope where that target applies. ".repeat(10);
  const longConstraints = Array.from({ length: 7 }, (_, index) => ({ ...constraint!, id: `layout_${index}`, description: `Payment target ${index + 1}. ${longDescription}` }));
  const layoutResponse = await request.post(base, { data: {
    norm: { ...original.norm, constraints: longConstraints, views: [{ name: "Finance", constraint_weights: Object.fromEntries(longConstraints.map(c => [c.id, 1])) }] },
    parentId: VERSION, note: "Synthetic review layout fixture with seven long definitions",
  } });
  expect(layoutResponse.status()).toBe(201);
  const layoutVersion = await layoutResponse.json() as { id: string };
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(`/p/${PROJECT}/norms/${layoutVersion.id}?tab=review&caseTable=${CASE_TABLE}`);
  await page.getByRole("button", { name: "Complete review decisions", exact: true }).click();
  const list = dialog.getByRole("list", { name: "Required decisions" });
  await expect(list.getByRole("button")).toHaveCount(7);
  await expect(list.getByRole("button").first()).toHaveAttribute("title", longConstraints[0]!.description);
  const footer = dialog.getByTestId("review-footer");
  await expect(footer).toBeInViewport({ ratio: 1 });
  const footerBox = await footer.boundingBox();
  expect(footerBox).not.toBeNull();
  expect(footerBox!.y).toBeGreaterThan(0);
  expect(footerBox!.y + footerBox!.height).toBeLessThanOrEqual(720);
  const reasonBox = await dialog.getByLabel("Reason for this constraint (required)").boundingBox();
  const ownerBox = await dialog.getByLabel("Constraint owner (required)").boundingBox();
  expect(reasonBox!.y + reasonBox!.height).toBeLessThanOrEqual(footerBox!.y);
  expect(ownerBox!.y + ownerBox!.height).toBeLessThanOrEqual(footerBox!.y);
  const titleHeights = await list.getByTestId("review-nav-title").evaluateAll(elements => elements.map(el => ({
    height: el.getBoundingClientRect().height, lineHeight: Number.parseFloat(el.ownerDocument.defaultView!.getComputedStyle(el).lineHeight),
  })));
  expect(titleHeights.every(box => box.height <= box.lineHeight * 2 + 1)).toBe(true);
  const listSize = await list.evaluate(el => ({ height: el.clientHeight, content: el.scrollHeight }));
  expect(listSize.content).toBeGreaterThan(listSize.height);
  await list.hover(); await page.mouse.wheel(0, 600);
  await expect.poll(() => list.evaluate(el => el.scrollTop)).toBeGreaterThan(0);
  expect(await footer.boundingBox()).toEqual(footerBox);
  await list.getByRole("button").last().click();
  await expect(dialog.getByLabel("Reason for this constraint (required)")).toBeFocused();
  await dialog.getByText("Full constraint meaning and rule", { exact: true }).click();
  await expect(dialog.getByTestId("review-meaning")).toContainText(longConstraints[6]!.description.trim());
  await expect(dialog.getByLabel("Constraint owner (required)")).toBeInViewport({ ratio: 1 });
  await expect(dialog.getByRole("button", { name: "Record decision", exact: true })).toBeInViewport({ ratio: 1 });
  expect(await footer.boundingBox()).toEqual(footerBox);
  await page.screenshot({ path: testInfo.outputPath("preflight-long-descriptions.png"), fullPage: true });
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  expect((await (await request.get(`${base}/${layoutVersion.id}`)).json()).status).toBe("draft");
  expect(pageErrors).toEqual([]);
});
